VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsRamalModel"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Adiciona uma linha de um novo ramal
Public Function RamalAdicionaLinha()

End Function
'Adiciona um ponto de uma ligação de água, sem adicionar o consumidor
Public Function RamalAdicionaPonto()

End Function
'Associa um consumidor a uma ligação de água
Public Function RamalAdicionaConsumidorAoPonto()

End Function
'Retira um consumidore de uma ligação de água
Public Function RamalRetiraConsumidorDoPonto()

End Function
'Adiciona os atributos de um ramal ao ramal
Public Function RamalAdicionaAtributosALinhaDoRamal()

End Function
