VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsRamalController"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Cadastra a linha do ramal da ligação de água
'
'
'
Public Function RamalDesenhaRamal()

End Function
'Cadastra um ponto de uma ligação pela primeira vez, sem cadastrar o consumidor, preparando para cadastrar o consumidor depois
'
'
'
Public Function RamalDesenhaLigacao()

End Function
'Adiciona um consumidor conhecido a uma ligação de água
Public Function RamalAdicionaLigacao()

End Function
'Identifica um consumidore existente a partir de dados obtidos em campo por leitura com dados GPS
'
'
'
Public Function RamalIdentificaConsumidor()

End Function
'Retira um consumidor existente que está associado a uma ligação de água
Public Function RamalRetiraConsumidor()

End Function
'Adiciona os atributos do ramal ao mesmo
Public Function RamalAdicionaAtributos()

End Function
