USE [geosan]
GO
/****** Object:  StoredProcedure [dbo].[atualizaClientesDoSistemaComercial]    Script Date: 05/29/2024 09:08:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		José Maria Villac Pinheiro
-- Create date: 24/02/2022
-- Description:	Atualiza a tabela com os dados so sistema comercial, com o objetivo do sistema rodar maisr rapidamente
-- NXGS_V_LIG_COMERCIAL_CONEXAO - é a vista conectada diretamente ao sistema comercial
-- =============================================
ALTER PROCEDURE [dbo].[atualizaClientesDoSistemaComercial]
AS
BEGIN
	IF OBJECT_ID ('dbo.NXGS_V_LIG_COMERCIAL') IS NOT NULL
	    BEGIN
	      DELETE FROM [dbo].[NXGS_V_LIG_COMERCIAL]
	      INSERT INTO [dbo].[NXGS_V_LIG_COMERCIAL]
					([NRO_LIGACAO],[NRO_LIGACAO_SEM_DV],[CLASSIFICACAO_FISCAL],[COD_LOGRADOURO],[ENDERECO],[NUM_CASA],[COMPL_LOGRADOURO],[BAIRRO],[HIDROMETRO],[COD_CONSUMIDOR],[COD_CONSUMIDOR_SEM_DV],[CONSUMIDOR],[TEL_RES],[TIPO],[ECONOMIAS],[HIDROMETRADO],[GRUPO_LEITURA],[ROTEIRO_LEITURA],[SEQUENCIA_LEITURA])
	      SELECT CAST(CODLIGACAO+'0' AS INT) AS CODLIGACAO,CAST(CAST(CODLIGACAO AS INT) AS VARCHAR(20)) AS CODLIGACAO2,'' AS CLASSIFICACAO_FISCAL,''AS COD_LOGRADOURO,LEFT(TIPOLOGRADOURO + ' ' + NOMELOGRADOURO, 294) AS ENDERECO,NUMEROENDERECO,LEFT(COMPLEMENTO,60) AS COMPL_LOGRADOURO,LEFT(NOMEBAIRRO,150) AS BAIRRO,LEFT(NUMEROHIDROMETRO,30) AS HIDROMETRO,CODINQUILINO+ '0' AS COD_CONSUMIDOR,CODINQUILINO AS COD_CONSUMIDOR_SEM_DV,LEFT(NOMEINQUILINO,150) AS CONSUMIDOR,FONEINQUILINO AS TEL_RES,CODCATEGORIA,NUMEROECONOMIA,CODSITUACAOLIGACAO,SETORLEITURA, ROTALEITURA, SEQUENCIALEITURA 
	        FROM
						OPENQUERY(FIREBIRD25, 
							'SELECT CODLIGACAO,TIPOLOGRADOURO,NOMELOGRADOURO ,NUMEROENDERECO,COALESCE(COMPLEMENTO, '''') AS COMPLEMENTO,NOMEBAIRRO,NUMEROHIDROMETRO,CODINQUILINO,COALESCE(NOMEINQUILINO,'''') AS NOMEINQUILINO,FONEINQUILINO,COALESCE(CODCATEGORIA,'''') AS CODCATEGORIA,NUMEROECONOMIA,CODSITUACAOLIGACAO,SETORLEITURA, ROTALEITURA, SEQUENCIALEITURA FROM VW_LIGACOES');
    END
	ELSE
	    BEGIN
	      INSERT INTO [dbo].[NXGS_V_LIG_COMERCIAL]
					([NRO_LIGACAO],[NRO_LIGACAO_SEM_DV],[CLASSIFICACAO_FISCAL],[COD_LOGRADOURO],[ENDERECO],[NUM_CASA],[COMPL_LOGRADOURO],[BAIRRO],[HIDROMETRO],[COD_CONSUMIDOR],[COD_CONSUMIDOR_SEM_DV],[CONSUMIDOR],[TEL_RES],[TIPO],[ECONOMIAS],[HIDROMETRADO],[GRUPO_LEITURA],[ROTEIRO_LEITURA],[SEQUENCIA_LEITURA])
	      SELECT CAST(CODLIGACAO+'0' AS INT) AS CODLIGACAO,CAST(CAST(CODLIGACAO AS INT) AS VARCHAR(20)) AS CODLIGACAO2,'' AS CLASSIFICACAO_FISCAL,''AS COD_LOGRADOURO,LEFT(TIPOLOGRADOURO + ' ' + NOMELOGRADOURO, 294) AS ENDERECO,NUMEROENDERECO,LEFT(COMPLEMENTO,60) AS COMPL_LOGRADOURO,LEFT(NOMEBAIRRO,150) AS BAIRRO,LEFT(NUMEROHIDROMETRO,30) AS HIDROMETRO,CODINQUILINO+ '0' AS COD_CONSUMIDOR,CODINQUILINO AS COD_CONSUMIDOR_SEM_DV,LEFT(NOMEINQUILINO,150) AS CONSUMIDOR,FONEINQUILINO AS TEL_RES,CODCATEGORIA,NUMEROECONOMIA,CODSITUACAOLIGACAO,SETORLEITURA, ROTALEITURA, SEQUENCIALEITURA 
	        FROM
						OPENQUERY(FIREBIRD25, 
							'SELECT CODLIGACAO,TIPOLOGRADOURO,NOMELOGRADOURO ,NUMEROENDERECO,COALESCE(COMPLEMENTO, '''') AS COMPLEMENTO,NOMEBAIRRO,NUMEROHIDROMETRO,CODINQUILINO,COALESCE(NOMEINQUILINO,'''') AS NOMEINQUILINO,FONEINQUILINO,COALESCE(CODCATEGORIA,'''') AS CODCATEGORIA,NUMEROECONOMIA,CODSITUACAOLIGACAO,SETORLEITURA, ROTALEITURA, SEQUENCIALEITURA FROM VW_LIGACOES');
	    END
	SET NOCOUNT ON;
END

